---
template_variables:
  book_title: VMware Tanzu Documentation
  book_title_short: VMware Tanzu Docs
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware's enterprise-grade software."
  k8s_runtime_full: VMware Enterprise PKS
  k8s_runtime_abbr: PKS
  platform_name: Pivotal Platform
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_full: Developer Console
  product_abbr: PDC
  product_short: Developer Console
  ops_manager: Ops Manager
  app_runtime_full: VMware Tanzu Application Service for VMs
  app_runtime_abbr: TAS for VMs
  product_link: <div class="header-item"><a href="https://network.pivotal.io/products/pivotal-cf">Back to Product Page</a></div>
  product_url:
  service_name: Developer Console
  service_name_article: Developer Console
  service_name_article_full: the Developer Console
  support_call_to_action: <a href="http://support.pivotal.io" target="_blank">Need Support?</a>
  support_link: <a href="http://support.pivotal.io" target="_blank">Support</a>
  support_url: http://support.pivotal.io
  tile_name: Developer Console
  title: <span class="title-deemph">VMware Tanzu</span> Documentation
  title_image: images/icon-p-green.jpg
  path_to_partials: /developer-console/partials
  product_network: VMware Tanzu Network
  windows_runtime_full: VMware Tanzu Application Service for VMs &#91;Windows&#93;
  windows_runtime_abbr: TAS for VMs &#91;Windows&#93;

  api_version: 235
  gtm_account_id: GTM-MW4LZHR

  use_global_header: true
  global_header_product_href: https://network.pivotal.io/
  global_header_product_link_text: Downloads
